- name: Check if Topbeat is already at the right version
  shell: dpkg -s topbeat | grep Version | awk '{print $2}'
  register: installed_version
  check_mode: no
  ignore_errors: True
  changed_when: False

- name: Download Topbeat agent
  get_url:
    url: "{{ topbeat_apt_repository }}"
    dest: /tmp
  when: installed_version.stdout != '{{ topbeat_version_check }}'

- name: Install Topbeat agent
  apt: deb="/tmp/{{ topbeat_apt_package_name }}"
  when: installed_version.stdout != '{{ topbeat_version_check }}' and not ansible_check_mode

- name: Create directory for Filebeat Configures
  file: path=/var/log/topbeat state=directory

- name: Configure Topbeat
  template:
    src: topbeat.yml.j2
    dest: /etc/topbeat/topbeat.yml
  notify: restart topbeat

- name: Index Topbeat Elasticsearch
  shell: curl -XPUT "http://{{ topbeat_elasticsearch_host }}/_template/topbeat" -d@/etc/topbeat/topbeat.template.json
  when: topbeat_redis_proxy is not defined

# - name: Index Topbeat Elasticsearch
#   shell: curl --proxy '{{ topbeat_redis_proxy }}' -XPUT "http://{{ topbeat_elasticsearch_host }}/_template/topbeat" -d@/etc/topbeat/topbeat.template.json
#   when: topbeat_redis_proxy is defined

- name: Starting Topbeat
  service: name=topbeat state=started enabled=yes
  ignore_errors: "{{ ansible_check_mode }}"
